### ISSUE TITLE
Include context information in play response

### ISSUE THREAD

**Issue by jtjeferreira** [kamon-io/kamon-play#29]
One missing feature from the 0.6.x days regarding the "automatic-trace-token-propagation" is that the trace token (now TraceId) is not present on the response:

https://github.com/kamon-io/kamon-play/blob/6558df23cd264cea6111ef8d4979ba4909cc04bb/kamon-play-2.5.x/src/main/resources/reference.conf#L13-L15

**Comment by ivantopo** [comment]
Hey @jtjeferreira, I'm closing this issue because it was somehow fixed by the new HTTP Server instrumentation. It is not possible to write anything on the response headers, only the TraceID and SpanID (check [these config settings](https://github.com/kamon-io/kamon-play/blob/master/kamon-play/src/main/resources/reference.conf#L98-L105)) but I'm sure that we will not be adding any additional processing there at the moment.
